---
- hosts: monitored
  gather_facts: yes
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=86400

  roles:
    - geerlingguy.filebeat
    - geerlingguy.munin-node
    - Mooash.nagios-nrpe-server
